let currentMode='moment';const uploadedFiles=[];let analyzing=!1;
const homePage=document.getElementById('homePage'),uploadPage=document.getElementById('uploadPage'),drawPage=document.getElementById('drawPage'),uploadTitle=document.getElementById('uploadTitle'),fileInput=document.getElementById('fileInput'),filePreview=document.getElementById('filePreview'),analyzeUploadBtn=document.getElementById('analyzeUploadBtn'),msgContainer=document.getElementById('msgContainer'),resultContainer=document.getElementById('resultContainer');
window.goBack=()=>{uploadPage.classList.remove('active');drawPage.classList.remove('active');homePage.classList.add('active')};
document.querySelectorAll('.feature-card').forEach(c=>{c.addEventListener('click',()=>{const m=c.dataset.mode;currentMode=m;homePage.classList.remove('active');if(m==='htp'){drawPage.classList.add('active');initCanvas()}else{uploadPage.classList.add('active');uploadTitle.textContent=m==='moment'?'朋友圈读心':'聊天风格分析';uploadedFiles.length=0;renderFileList();analyzeUploadBtn.disabled=!0}})});
const uploadArea=document.getElementById('uploadArea');uploadArea.addEventListener('click',()=>fileInput.click());uploadArea.addEventListener('dragover',e=>{e.preventDefault();uploadArea.style.background='#F0FDF4'});uploadArea.addEventListener('dragleave',()=>uploadArea.style.background='');uploadArea.addEventListener('drop',e=>{e.preventDefault();uploadArea.style.background='';addFiles(Array.from(e.dataTransfer.files).filter(f=>f.type.startsWith('image/')))});fileInput.addEventListener('change',e=>{addFiles(Array.from(e.target.files));fileInput.value=''});
function addFiles(files){for(const f of files){if(uploadedFiles.length>=3){alert('最多3张');break}if(f.size>10*1024*1024){alert('图片不超过10MB');continue}uploadedFiles.push(f)}renderFileList();analyzeUploadBtn.disabled=uploadedFiles.length===0}
function renderFileList(){filePreview.innerHTML=uploadedFiles.map((f,i)=>`<div class="file-item"><span><i class="fas fa-image"></i> ${f.name}</span><button class="remove-btn" onclick="removeFile(${i})"><i class="fas fa-times"></i></button></div>`).join('')}
window.removeFile=i=>{uploadedFiles.splice(i,1);renderFileList();analyzeUploadBtn.disabled=uploadedFiles.length===0};
document.getElementById('clearUploadBtn').addEventListener('click',()=>{uploadedFiles.length=0;renderFileList();analyzeUploadBtn.disabled=!0});
async function compressImage(file){return new Promise(r=>{const reader=new FileReader();reader.onload=e=>{const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');let w=img.width,h=img.height;if(w>1200){h=h*1200/w;w=1200}canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);canvas.toBlob(b=>r(new File([b],file.name,{type:'image/jpeg'})),'image/jpeg',0.8)};img.src=e.target.result};reader.readAsDataURL(file)})}
function fileToBase64(file){return new Promise((r,e)=>{const reader=new FileReader();reader.onload=()=>r(reader.result);reader.onerror=e;reader.readAsDataURL(file)})}
async function submitAnalysis(type,imageBase64Array,selfDesc=''){if(analyzing)return;analyzing=!0;showMessage('progress','AI分析中...');try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,images:imageBase64Array,selfDesc})});const data=await res.json();if(!data.success)throw new Error(data.error);showMessage('success','分析完成');resultContainer.style.display='block';resultContainer.innerHTML=`<pre>${data.result}</pre>`}catch(e){showMessage('error',e.message)}finally{analyzing=!1}}
analyzeUploadBtn.addEventListener('click',async()=>{const base64Array=[];for(const f of uploadedFiles){try{const c=await compressImage(f);const b64=await fileToBase64(c);base64Array.push(b64)}catch(e){showMessage('error',e.message);return}}submitAnalysis(currentMode,base64Array)});
const canvas=document.getElementById('drawingCanvas'),ctx=canvas.getContext('2d');let drawing=!1,eraser=!1,lastX,lastY,history=[],MAX_HISTORY=30;
function initCanvas(){ctx.fillStyle='#FFFFFF';ctx.fillRect(0,0,canvas.width,canvas.height);history=[];saveState()}
function saveState(){history.push(ctx.getImageData(0,0,canvas.width,canvas.height));if(history.length>MAX_HISTORY)history.shift()}
function undo(){if(history.length>1){history.pop();ctx.putImageData(history[history.length-1],0,0)}}
function getCoords(e){const rect=canvas.getBoundingClientRect(),sx=canvas.width/rect.width,sy=canvas.height/rect.height,cx=e.touches?e.touches[0].clientX:e.clientX,cy=e.touches?e.touches[0].clientY:e.clientY;return{x:Math.min(canvas.width,Math.max(0,(cx-rect.left)*sx)),y:Math.min(canvas.height,Math.max(0,(cy-rect.top)*sy))}}
function startDraw(e){e.preventDefault();const{x,y}=getCoords(e);drawing=!0;lastX=x;lastY=y;saveState();if(!eraser){ctx.beginPath();ctx.arc(x,y,ctx.lineWidth/2,0,2*Math.PI);ctx.fillStyle=document.querySelector('.color-btn.active').dataset.color;ctx.fill()}}
function draw(e){e.preventDefault();if(!drawing)return;const{x,y}=getCoords(e);ctx.beginPath();ctx.moveTo(lastX,lastY);ctx.lineTo(x,y);ctx.strokeStyle=eraser?'#FFFFFF':document.querySelector('.color-btn.active').dataset.color;ctx.lineWidth=parseInt(document.querySelector('.size-btn.active').dataset.size);ctx.lineCap='round';ctx.stroke();lastX=x;lastY=y}
function endDraw(e){e.preventDefault();drawing=!1}
canvas.addEventListener('pointerdown',startDraw);canvas.addEventListener('pointermove',draw);canvas.addEventListener('pointerup',endDraw);canvas.addEventListener('pointercancel',endDraw);
document.querySelectorAll('.color-btn').forEach(b=>b.addEventListener('click',function(){document.querySelectorAll('.color-btn').forEach(c=>c.classList.remove('active'));this.classList.add('active');eraser=!1;document.getElementById('eraserBtn').classList.remove('active')}));
document.querySelectorAll('.size-btn').forEach(b=>b.addEventListener('click',function(){document.querySelectorAll('.size-btn').forEach(s=>s.classList.remove('active'));this.classList.add('active')}));
document.getElementById('eraserBtn').addEventListener('click',function(){eraser=!eraser;this.classList.toggle('active',eraser)});
document.getElementById('undoBtn').addEventListener('click',undo);
document.getElementById('clearCanvasBtn').addEventListener('click',()=>{ctx.fillStyle='#FFFFFF';ctx.fillRect(0,0,canvas.width,canvas.height);history=[];saveState()});
document.getElementById('analyzeDrawingBtn').addEventListener('click',()=>{const dataURL=canvas.toDataURL('image/png');submitAnalysis('htp',[dataURL],document.getElementById('selfDescInput').value)});
document.getElementById('selfDescInput').addEventListener('input',e=>{document.getElementById('charCount').textContent=e.target.value.length});
const customColorBtn=document.getElementById('customColorBtn'),colorPicker=document.getElementById('colorPicker');
customColorBtn.addEventListener('click',()=>colorPicker.click());
colorPicker.addEventListener('input',e=>{const color=e.target.value;customColorBtn.querySelector('.custom-dot').style.background=color;customColorBtn.dataset.color=color;document.querySelectorAll('.color-btn').forEach(b=>b.classList.remove('active'));customColorBtn.classList.add('active');eraser=!1;document.getElementById('eraserBtn').classList.remove('active')});
function showMessage(type,text){msgContainer.innerHTML=`<div class="msg msg-${type}"><i class="fas fa-${type==='progress'?'spinner fa-pulse':(type==='error'?'exclamation-circle':'check-circle')}"></i>${text}</div>`;if(type!=='progress')setTimeout(()=>msgContainer.innerHTML='',4000)}
