let adminSecret=sessionStorage.getItem('adminSecret')||'';const API='/api';
async function apiCall(endpoint,options={}){const r=await fetch(`${API}${endpoint}`,{...options,headers:{'Content-Type':'application/json','X-Admin-Secret':adminSecret,...options.headers}}),d=await r.json();if(!d.success)throw new Error(d.error);return d.data}
document.getElementById('loginBtn').addEventListener('click',async()=>{const s=document.getElementById('adminSecret').value;adminSecret=s;try{await apiCall('/auth',{method:'POST',body:JSON.stringify({secret:s})});sessionStorage.setItem('adminSecret',s);document.getElementById('loginPanel').style.display='none';document.getElementById('adminPanel').style.display='block';loadDashboard();loadConfigs()}catch(e){document.getElementById('loginError').textContent=e.message}});
window.logout=()=>{sessionStorage.removeItem('adminSecret');location.reload()};
let trendChart,providerChart;
async function loadDashboard(){const s=await apiCall('/stats');document.getElementById('totalTasks').textContent=s.total;document.getElementById('successTasks').textContent=s.success;document.getElementById('failedTasks').textContent=s.failed;const c1=document.getElementById('trendChart').getContext('2d');trendChart&&trendChart.destroy();trendChart=new Chart(c1,{type:'line',data:{labels:s.daily.map(d=>d.day),datasets:[{label:'任务量',data:s.daily.map(d=>d.count),borderColor:'#2EBD85',tension:0.3}]}});const c2=document.getElementById('providerChart').getContext('2d');providerChart&&providerChart.destroy();providerChart=new Chart(c2,{type:'bar',data:{labels:s.providers.map(p=>p.provider||'unknown'),datasets:[{label:'调用次数',data:s.providers.map(p=>p.count),backgroundColor:'#2EBD85'}]}})}
async function loadConfigs(){const c=await apiCall('/config');c.forEach(c=>{const e=document.getElementById(`cfg_${c.key}`);if(e)e.value=c.value})}
document.getElementById('saveAllConfigs').addEventListener('click',async()=>{const k=['ai_provider','siliconflow_api_key','deepseek_api_key','cloudflare_account_id','cloudflare_api_token','admin_secret','announcement'];for(const key of k){const v=document.getElementById(`cfg_${key}`).value;await apiCall('/config-update',{method:'POST',body:JSON.stringify({key,value:v})})}alert('配置已保存')});
document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',function(){document.querySelectorAll('.tab-btn').forEach(t=>t.classList.remove('active'));this.classList.add('active');document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));document.getElementById(`tab-${this.dataset.tab}`).classList.add('active');if(this.dataset.tab==='tasks')loadTasks()}));
async function loadTasks(page=1){const s=document.getElementById('filterStatus').value,t=document.getElementById('filterType').value,p=new URLSearchParams({page,limit:20,status:s,type:t}),d=await apiCall(`/tasks?${p}`),b=document.getElementById('tasksTableBody');b.innerHTML=d.tasks.map(t=>`<tr><td>${t.id.slice(0,8)}</td><td>${t.type}</td><td>${t.status}</td><td>${t.provider}</td><td>${new Date(t.created_at*1000).toLocaleString()}</td><td><button onclick="viewTask('${t.id}')">查看</button></td></tr>`).join('')}
window.viewTask=async id=>{const t=await apiCall(`/task?id=${id}`);alert(JSON.stringify(t,null,2))};
document.getElementById('searchTasksBtn').addEventListener('click',()=>loadTasks());
if(adminSecret){apiCall('/auth',{method:'POST',body:JSON.stringify({secret:adminSecret})}).then(()=>{document.getElementById('loginPanel').style.display='none';document.getElementById('adminPanel').style.display='block';loadDashboard();loadConfigs()}).catch(()=>{sessionStorage.removeItem('adminSecret');adminSecret=''})}
